### Get Users

GET http://localhost:8080/users

### Get User by ID
GET http://localhost:8080/users/2

### Add User
POST http://localhost:8080/users/addUser
Content-Type: application/json

{
    "name": "Mike"
}

### Get articles
GET http://localhost:8080/articles

### Get article by ID
GET http://localhost:8080/articles/1

### Get books
GET http://localhost:8080/books

### Get book by id
GET http://localhost:8080/books/1

### Get topics
GET http://localhost:8080/topics

### Get sessions
GET http://localhost:8080/sessions

### Add a session
POST http://localhost:8080/users/2/addSession
Content-Type: application/json

{
    "date": "4/6/22",
    "duration": 20,
    "note": "Third eye completely shut."
}
