###
GET https://zenquotes.io/api/random/32bcf235078efe18922329c8829e0c88e4a2098a

###
GET http://localhost:8080/users

###

GET http://localhost:8080/users/1


###

GET http://localhost:8080/mindset-cards

###
GET http://localhost:8080//topics



###
POST http://localhost:8080/mindset-cards/add-why-card
Content-Type: application/json

 {
    "front": "why30",
    "back": "This is the back of mindset card 30"
  }


###
DELETE http://localhost:8080/mindset-why-cards/30/delete


###
GET http://localhost:8080/users/1/mindset-wins-cards

###
GET http://localhost:8080/users/1/mindset-why-cards





