###
GET https://zenquotes.io/api/random/32bcf235078efe18922329c8829e0c88e4a2098a

###
GET http://localhost:8080/users

###

GET http://localhost:8080/users/1

###

GET http://localhost:8080/users/2


###
GET http://localhost:8080//topics



###
POST http://localhost:8080/user/1/mindset-cards/add-why-card
Content-Type: application/json

{
    "front": "win9",
    "back": "This is the back of mindset card 4",
    "userId": 2
}


###
POST http://localhost:8080/users/1/mindset-cards/add-why-card
Content-Type: application/json

  {
  
    "front": "why1000",
    "back": "This is the back of mindset card sdsvdsds4",
    "userId": 1
  }


###
DELETE http://localhost:8080/user/1/mindset-why-cards/31/delete




###
GET http://localhost:8080/users/1/mindset-wins-cards

###
GET http://localhost:8080/users/1/mindset-why-cards



###
GET http://localhost:8080/users/2/mindset-wins-cards

###
GET http://localhost:8080/users/2/mindset-why-cards





